In [1]:
import pandas as pd

In [2]:
df1 = pd.read_excel('ST-GWC Debit ID 6001363_(DISPUTED CLAIMS) 05122023.xlsx')

In [3]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 694 entries, 0 to 693
Data columns (total 42 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Model Year                                         693 non-null    float64
 1   Labor Hours                                        693 non-null    float64
 2   Labor hours adjusted to .4 per sensor              694 non-null    float64
 3   Material Cost adjusted to 64.47 per sensor         694 non-null    float64
 4   Part MarkUp Adjusted to 18.42 per sensor           694 non-null    float64
 5   Misc. Amt (total)                                  694 non-null    float64
 6   Custom Column                                      693 non-null    float64
 7   Customer Paid Amount                               693 non-null    float64
 8   Repair Dealer Paid Amount                          693 non-null    float64
 9   Total Cost Gross                                   694 non-null    float64
 10  Claim Key                                          693 non-null    float64
 11  VIN                                                693 non-null    object
 12  Repair Dealer Code                                 693 non-null    object
 13  Document Number                                    693 non-null    object
 14  Part Num Full OB (Causal)                          693 non-null    object
 15  Part Num Prefix (Causal)                           693 non-null    object
 16  Part Num Base (Causal)                             693 non-null    object
 17  Part Num Suffix (Causal)                           693 non-null    object
 18  Vehicle Line AWS                                   693 non-null    object
 19  Mileage                                            693 non-null    float64
 20  Load Date                                          693 non-null    datetime64[ns]
 21  Repair Date                                        693 non-null    datetime64[ns]
 22  Repair Dealer State                                693 non-null    object
 23  Country Repaired                                   693 non-null    object
 24  Region Repaired                                    40 non-null     object
 25  Production Date                                    693 non-null    datetime64[ns]
 26  Warranty Start Date                                690 non-null    datetime64[ns]
 27  Country Sold                                       693 non-null    object
 28  Customer Concern Code                              693 non-null    object
 29  Customer Comments                                  693 non-null    object
 30  Condition Code                                     693 non-null    object
 31  Technician Comments                                690 non-null    object
 32  Part Install Date                                  682 non-null    object
 33  Transaction Code                                   693 non-null    object
 34  Part Quantity                                      693 non-null    float64
 35  Original Labor Cost                                693 non-null    float64
 36  Original Material Cost                             693 non-null    float64
 37  Original Part MarkUp Adjusted to 18.42 per sensor  693 non-null    float64
 38  SUPPLIER DISPUTES VALIDITY?                        212 non-null    object
 39  Supplier A DISPUTE REASON                          212 non-null    object
 40  Unnamed: 40                                        0 non-null      float64
 41  Time In Service
(in years)                         693 non-null    float64
dtypes: datetime64[ns](4), float64(18), object(20)
memory usage: 227.8+ KB

In [4]:
df = df1.iloc[:, :-3]

In [5]:
df

,Model Year,Labor Hours,Labor hours adjusted to .4 per sensor,Material Cost adjusted to 64.47 per sensor,Part MarkUp Adjusted to 18.42 per sensor,Misc. Amt (total),Custom Column,Customer Paid Amount,Repair Dealer Paid Amount,Total Cost Gross,...,Customer Comments,Condition Code,Technician Comments,Part Install Date,Transaction Code,Part Quantity,Original Labor Cost,Original Material Cost,Original Part MarkUp Adjusted to 18.42 per sensor,SUPPLIER DISPUTES VALIDITY?
0,2020.0,0.6,70.94,128.94,36.84,0.000000,0.0,0.0,0.0,199.88,...,CHECK TO FRONT RIMS WHEN FILL WITH AIR THE RIM...,D4,PRIOR APPRIVAL CONTACT IN NUMBER 11 9869794***...,01-JAN-0001,E84,2.0,100.720000,17164.330000,8116.190000,X
1,2021.0,14.2,35.47,64.47,18.42,0.000000,0.0,0.0,0.0,99.94,...,LITE: REPAIR/LITE DUTY GUEST STATES WHILE DRIV...,42,"verified concern, inspected right rear axle, r...",01-JAN-0001,E95,1.0,1914.160000,7649.790000,3648.850000,X
2,2022.0,18.6,35.47,64.47,18.42,0.000000,0.0,0.0,0.0,99.94,...,CUSTOMER STATES ABS LIGHTON AND SMOKE FROM DRI...,42,INSPECTED AND FOUND OIL AROUND THE LEFT REAR W...,01-JAN-0001,1,1.0,2439.770000,5767.070000,2777.400000,X
3,2021.0,14.6,35.47,64.47,18.42,483.563159,0.0,0.0,0.0,99.94,...,TOW IN- CHECK AND ADVISE FOR LEFT REAR TIRES A...,42,"656237 4205A 1.8, 4205A13G 5.6, 1007AE 0.6 ATT...",01-JAN-0001,E95,1.0,1790.462770,5236.397856,1494.541532,X
4,2022.0,1.2,141.88,257.88,73.68,0.000000,0.0,0.0,0.0,399.76,...,MISBUILT UNIT . TRUCK WAS SOLD WITH TIRES SIZE...,38,- TECH REPLACED 4 TIRES AND WHEELS AFTER GETTI...,01-JAN-0001,MVC,4.0,300.000000,4923.440000,2300.400000,X
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
689,2022.0,0.4,35.47,64.47,18.42,2.457425,0.0,0.0,0.0,99.94,...,"INSPECT LEAKING PASS FRONT VALVE STEM LEAKING,...",42,REPLACED RIGHT FRONT VALVE STEM. SET TIRE PRES...,01-JAN-0001,1,1.0,44.187852,5.014062,1.434770,NaN
690,2022.0,0.4,35.47,64.47,18.42,5.693288,0.0,0.0,0.0,99.94,...,CUSTOMER THERE IS SLOW LEAK IN THE FRONT PASSE...,1,"1007 STEM REPLACED, 1552AA, VALVE WAS LEAKING,...",01-JAN-0001,E84,1.0,39.959861,3.823508,1.091341,X
691,2022.0,0.4,35.47,64.47,18.42,4.601947,0.0,0.0,0.0,99.94,...,CONCERN; TIRE CONCERN. CHECK WHY TIRES SLOW LEAK,42,TIRE CONCERN. CHECK WHY TIRES SLOW LEAK FOUND ...,01-JAN-0001,1,1.0,26.848508,3.823508,1.091341,X
692,2022.0,0.8,35.47,64.47,18.42,0.000000,0.0,0.0,0.0,99.94,...,CHECK AND REPORT ON TYRE PRESSURE MALFUNCTION ...,42,CHECKED AND FOUND L/H/R SENSOR NOT CALIBRATING...,NaN,*,1.0,0.000000,0.000000,0.000000,NaN
693,NaN,NaN,30220.44,54928.44,15693.84,3946.861408,NaN,NaN,NaN,85148.88,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 694 entries, 0 to 693
Data columns (total 39 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Model Year                                         693 non-null    float64
 1   Labor Hours                                        693 non-null    float64
 2   Labor hours adjusted to .4 per sensor              694 non-null    float64
 3   Material Cost adjusted to 64.47 per sensor         694 non-null    float64
 4   Part MarkUp Adjusted to 18.42 per sensor           694 non-null    float64
 5   Misc. Amt (total)                                  694 non-null    float64
 6   Custom Column                                      693 non-null    float64
 7   Customer Paid Amount                               693 non-null    float64
 8   Repair Dealer Paid Amount                          693 non-null    float64
 9   Total Cost Gross                                   694 non-null    float64
 10  Claim Key                                          693 non-null    float64
 11  VIN                                                693 non-null    object
 12  Repair Dealer Code                                 693 non-null    object
 13  Document Number                                    693 non-null    object
 14  Part Num Full OB (Causal)                          693 non-null    object
 15  Part Num Prefix (Causal)                           693 non-null    object
 16  Part Num Base (Causal)                             693 non-null    object
 17  Part Num Suffix (Causal)                           693 non-null    object
 18  Vehicle Line AWS                                   693 non-null    object
 19  Mileage                                            693 non-null    float64
 20  Load Date                                          693 non-null    datetime64[ns]
 21  Repair Date                                        693 non-null    datetime64[ns]
 22  Repair Dealer State                                693 non-null    object
 23  Country Repaired                                   693 non-null    object
 24  Region Repaired                                    40 non-null     object
 25  Production Date                                    693 non-null    datetime64[ns]
 26  Warranty Start Date                                690 non-null    datetime64[ns]
 27  Country Sold                                       693 non-null    object
 28  Customer Concern Code                              693 non-null    object
 29  Customer Comments                                  693 non-null    object
 30  Condition Code                                     693 non-null    object
 31  Technician Comments                                690 non-null    object
 32  Part Install Date                                  682 non-null    object
 33  Transaction Code                                   693 non-null    object
 34  Part Quantity                                      693 non-null    float64
 35  Original Labor Cost                                693 non-null    float64
 36  Original Material Cost                             693 non-null    float64
 37  Original Part MarkUp Adjusted to 18.42 per sensor  693 non-null    float64
 38  SUPPLIER DISPUTES VALIDITY?                        212 non-null    object
dtypes: datetime64[ns](4), float64(16), object(19)
memory usage: 211.6+ KB

In [7]:
# Convert 'hire_date' and 'current_date' columns to datetime objects
df['Warranty Start Date'] = pd.to_datetime(df['Warranty Start Date'])
df['Repair Date'] = pd.to_datetime(df['Repair Date'])

# Calculate the time in service as the difference between 'current_date' and 'hire_date' in years
df['time_in_service_years'] = (df['Repair Date'] - df['Warranty Start Date']).dt.days / 365.25  # Consider leap years

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 694 entries, 0 to 693
Data columns (total 40 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Model Year                                         693 non-null    float64
 1   Labor Hours                                        693 non-null    float64
 2   Labor hours adjusted to .4 per sensor              694 non-null    float64
 3   Material Cost adjusted to 64.47 per sensor         694 non-null    float64
 4   Part MarkUp Adjusted to 18.42 per sensor           694 non-null    float64
 5   Misc. Amt (total)                                  694 non-null    float64
 6   Custom Column                                      693 non-null    float64
 7   Customer Paid Amount                               693 non-null    float64
 8   Repair Dealer Paid Amount                          693 non-null    float64
 9   Total Cost Gross                                   694 non-null    float64
 10  Claim Key                                          693 non-null    float64
 11  VIN                                                693 non-null    object
 12  Repair Dealer Code                                 693 non-null    object
 13  Document Number                                    693 non-null    object
 14  Part Num Full OB (Causal)                          693 non-null    object
 15  Part Num Prefix (Causal)                           693 non-null    object
 16  Part Num Base (Causal)                             693 non-null    object
 17  Part Num Suffix (Causal)                           693 non-null    object
 18  Vehicle Line AWS                                   693 non-null    object
 19  Mileage                                            693 non-null    float64
 20  Load Date                                          693 non-null    datetime64[ns]
 21  Repair Date                                        693 non-null    datetime64[ns]
 22  Repair Dealer State                                693 non-null    object
 23  Country Repaired                                   693 non-null    object
 24  Region Repaired                                    40 non-null     object
 25  Production Date                                    693 non-null    datetime64[ns]
 26  Warranty Start Date                                690 non-null    datetime64[ns]
 27  Country Sold                                       693 non-null    object
 28  Customer Concern Code                              693 non-null    object
 29  Customer Comments                                  693 non-null    object
 30  Condition Code                                     693 non-null    object
 31  Technician Comments                                690 non-null    object
 32  Part Install Date                                  682 non-null    object
 33  Transaction Code                                   693 non-null    object
 34  Part Quantity                                      693 non-null    float64
 35  Original Labor Cost                                693 non-null    float64
 36  Original Material Cost                             693 non-null    float64
 37  Original Part MarkUp Adjusted to 18.42 per sensor  693 non-null    float64
 38  SUPPLIER DISPUTES VALIDITY?                        212 non-null    object
 39  time_in_service_years                              690 non-null    float64
dtypes: datetime64[ns](4), float64(17), object(19)
memory usage: 217.0+ KB

In [9]:
df['time_in_service_years']

0      1.902806
1      1.533196
2      0.837782
3      1.442847
4      0.136893
         ...
689    0.427105
690    0.996578
691    0.402464
692    0.169747
693         NaN
Name: time_in_service_years, Length: 694, dtype: float64

In [10]:
selected_columns = ['Mileage', 'time_in_service_years', 'Vehicle Line AWS', 'Customer Comments', 'Technician Comments']
df_selected = df[selected_columns]

In [11]:
df_selected

,Mileage,time_in_service_years,Vehicle Line AWS,Customer Comments,Technician Comments
0,11993.0,1.902806,ZA,CHECK TO FRONT RIMS WHEN FILL WITH AIR THE RIM...,PRIOR APPRIVAL CONTACT IN NUMBER 11 9869794***...
1,50704.0,1.533196,F7,LITE: REPAIR/LITE DUTY GUEST STATES WHILE DRIV...,"verified concern, inspected right rear axle, r..."
2,746.0,0.837782,E1,CUSTOMER STATES ABS LIGHTON AND SMOKE FROM DRI...,INSPECTED AND FOUND OIL AROUND THE LEFT REAR W...
3,37506.0,1.442847,E1,TOW IN- CHECK AND ADVISE FOR LEFT REAR TIRES A...,"656237 4205A 1.8, 4205A13G 5.6, 1007AE 0.6 ATT..."
4,123.0,0.136893,F7,MISBUILT UNIT . TRUCK WAS SOLD WITH TIRES SIZE...,- TECH REPLACED 4 TIRES AND WHEELS AFTER GETTI...
...,...,...,...,...,...
689,4482.0,0.427105,ZA,"INSPECT LEAKING PASS FRONT VALVE STEM LEAKING,...",REPLACED RIGHT FRONT VALVE STEM. SET TIRE PRES...
690,12993.0,0.996578,R2,CUSTOMER THERE IS SLOW LEAK IN THE FRONT PASSE...,"1007 STEM REPLACED, 1552AA, VALVE WAS LEAKING,..."
691,4565.0,0.402464,R2,CONCERN; TIRE CONCERN. CHECK WHY TIRES SLOW LEAK,TIRE CONCERN. CHECK WHY TIRES SLOW LEAK FOUND ...
692,472.0,0.169747,ZA,CHECK AND REPORT ON TYRE PRESSURE MALFUNCTION ...,CHECKED AND FOUND L/H/R SENSOR NOT CALIBRATING...
693,NaN,NaN,NaN,NaN,NaN

In [12]:
# Step 1: Create a new column 'validity' and initialize it as 'Accepted'
df['validity'] = ''

 

# Step 2 and 3: Apply the condition and set 'validity' to 'Rejected' for rows that meet the condition
condition = (df['Mileage'] > 36000) & (df['time_in_service_years'] > 3) & (df['Vehicle Line AWS'].isin(['M4', 'R2', 'ZE']))
df.loc[condition, 'validity'] = 'Rejected'

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 694 entries, 0 to 693
Data columns (total 41 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Model Year                                         693 non-null    float64
 1   Labor Hours                                        693 non-null    float64
 2   Labor hours adjusted to .4 per sensor              694 non-null    float64
 3   Material Cost adjusted to 64.47 per sensor         694 non-null    float64
 4   Part MarkUp Adjusted to 18.42 per sensor           694 non-null    float64
 5   Misc. Amt (total)                                  694 non-null    float64
 6   Custom Column                                      693 non-null    float64
 7   Customer Paid Amount                               693 non-null    float64
 8   Repair Dealer Paid Amount                          693 non-null    float64
 9   Total Cost Gross                                   694 non-null    float64
 10  Claim Key                                          693 non-null    float64
 11  VIN                                                693 non-null    object
 12  Repair Dealer Code                                 693 non-null    object
 13  Document Number                                    693 non-null    object
 14  Part Num Full OB (Causal)                          693 non-null    object
 15  Part Num Prefix (Causal)                           693 non-null    object
 16  Part Num Base (Causal)                             693 non-null    object
 17  Part Num Suffix (Causal)                           693 non-null    object
 18  Vehicle Line AWS                                   693 non-null    object
 19  Mileage                                            693 non-null    float64
 20  Load Date                                          693 non-null    datetime64[ns]
 21  Repair Date                                        693 non-null    datetime64[ns]
 22  Repair Dealer State                                693 non-null    object
 23  Country Repaired                                   693 non-null    object
 24  Region Repaired                                    40 non-null     object
 25  Production Date                                    693 non-null    datetime64[ns]
 26  Warranty Start Date                                690 non-null    datetime64[ns]
 27  Country Sold                                       693 non-null    object
 28  Customer Concern Code                              693 non-null    object
 29  Customer Comments                                  693 non-null    object
 30  Condition Code                                     693 non-null    object
 31  Technician Comments                                690 non-null    object
 32  Part Install Date                                  682 non-null    object
 33  Transaction Code                                   693 non-null    object
 34  Part Quantity                                      693 non-null    float64
 35  Original Labor Cost                                693 non-null    float64
 36  Original Material Cost                             693 non-null    float64
 37  Original Part MarkUp Adjusted to 18.42 per sensor  693 non-null    float64
 38  SUPPLIER DISPUTES VALIDITY?                        212 non-null    object
 39  time_in_service_years                              690 non-null    float64
 40  validity                                           694 non-null    object
dtypes: datetime64[ns](4), float64(17), object(20)
memory usage: 222.4+ KB

In [14]:
df.head()

,Model Year,Labor Hours,Labor hours adjusted to .4 per sensor,Material Cost adjusted to 64.47 per sensor,Part MarkUp Adjusted to 18.42 per sensor,Misc. Amt (total),Custom Column,Customer Paid Amount,Repair Dealer Paid Amount,Total Cost Gross,...,Technician Comments,Part Install Date,Transaction Code,Part Quantity,Original Labor Cost,Original Material Cost,Original Part MarkUp Adjusted to 18.42 per sensor,SUPPLIER DISPUTES VALIDITY?,time_in_service_years,validity
0,2020.0,0.6,70.94,128.94,36.84,0.000000,0.0,0.0,0.0,199.88,...,PRIOR APPRIVAL CONTACT IN NUMBER 11 9869794***...,01-JAN-0001,E84,2.0,100.72000,17164.330000,8116.190000,X,1.902806,
1,2021.0,14.2,35.47,64.47,18.42,0.000000,0.0,0.0,0.0,99.94,...,"verified concern, inspected right rear axle, r...",01-JAN-0001,E95,1.0,1914.16000,7649.790000,3648.850000,X,1.533196,
2,2022.0,18.6,35.47,64.47,18.42,0.000000,0.0,0.0,0.0,99.94,...,INSPECTED AND FOUND OIL AROUND THE LEFT REAR W...,01-JAN-0001,1,1.0,2439.77000,5767.070000,2777.400000,X,0.837782,
3,2021.0,14.6,35.47,64.47,18.42,483.563159,0.0,0.0,0.0,99.94,...,"656237 4205A 1.8, 4205A13G 5.6, 1007AE 0.6 ATT...",01-JAN-0001,E95,1.0,1790.46277,5236.397856,1494.541532,X,1.442847,
4,2022.0,1.2,141.88,257.88,73.68,0.000000,0.0,0.0,0.0,399.76,...,- TECH REPLACED 4 TIRES AND WHEELS AFTER GETTI...,01-JAN-0001,MVC,4.0,300.00000,4923.440000,2300.400000,X,0.136893,

# Handling abbreviations

In [15]:
abbreviations_df = pd.read_excel('ABBREV.xlsx')

FileNotFoundError: [Errno 2] No such file or directory: 'ABBREV.xlsx'

In [ ]:
abbreviations_df

In [16]:
abbreviations = dict(zip(abbreviations_df['Acronym'], abbreviations_df['Full Form']))

NameError: name 'abbreviations_df' is not defined

In [17]:
def replace_abbreviations(text):
    words = str(text).split()
    for i in range(len(words)):
        if words[i] in abbreviations:
            words[i] = abbreviations[words[i]]
    return ' '.join(words)

In [21]:
df['Technician Comments'] = df['Technician Comments'].apply(replace_abbreviations)
df['Customer Comments'] = df['Customer Comments'].apply(replace_abbreviations)

# Handling spellings

In [22]:
from spellchecker import SpellChecker
spell = SpellChecker()

In [23]:
def correct_spelling(text):
    corrected_words = []
    words = text.split()
    
    for word in words:
        corrected_word = spell.correction(word)
        if corrected_word is not None:
            corrected_words.append(corrected_word)
        else:
            corrected_words.append('')  # Replace None with empty string
    
    return ' '.join(corrected_words)

In [ ]:
df['Technician Comments'] = df['Technician Comments'].apply(correct_spelling)
df['Customer Comments'] = df['Customer Comments'].apply(correct_spelling)